### PR TITLE
Pass clients handshake failure information

### PR DESCRIPTION
**Pull request by AeroNotix**

### CODE REVIEW

**Comment by AeroNotix** [comment]
@ubnt-yhlee I branched off your changes in order to keep those changes live if we decided to merge this.

**Comment by ubnt-yhlee** [comment]
Change the base to `master`. Thanks for reminding that it was not merged.

A few thoughts:
1. I'd prefer following upstream spacing rules - it would be easier to upgrade
2. upstream just release 1.3.1 (yes, almost 4yr gap)
3. what's the reason we want to continue when server side give 400?

**Comment by AeroNotix** [comment]
I will change the base to `master`.

1. Whitespace changes are mostly in a separate commit. Though will ensure spacing rules are kept the same.
2. I'll look into grabbing those changes to see if they help.
3. Unless I'm mistaken, we don't? Only the `MATCHED` state will return a valid connection.

**Comment by ubnt-yhlee** [comment]
Ah I see. `onWebsocketHandshakeReceivedAsClient` is not really opening the connection, `open( handshake );` is. But when 400 is thrown, who's going to call flushAndClose?

**Comment by ubnt-yhlee** [comment]
replaced by #2

**Pull request closed without merging**
